import {escapeHTML as e} from './domain.mjs';
import {composeDraft} from './prospect.mjs?v=20261006-2';
export function openProspectDraft({dialog,record,brand,members,user,store,demo,canEdit,back}){
 if(record.status==='Ne plus contacter'||record.archived)return;
 const token=crypto.randomUUID(),controller=new AbortController();let scan=null;
 const team=members.filter(m=>m.brand_id===record.brand_id);const owner=team.find(m=>m.user_id===record.owner_id)||team.find(m=>m.user_id===user.id);
 const offer=brand.name.toLowerCase()==='nanayé'?'Nous proposons des maillots de bain pour les groupes, avec un choix de coupes et d’imprimés.':'';
 dialog.dataset.draft=token;
 dialog.innerHTML=`<div class="panel-head"><div><div class="eyebrow muted">${e(record.name)}</div><h2>Préparer un message</h2></div><button id="draft-close" aria-label="Fermer">✕</button></div><p class="muted">Analysez le site pour obtenir un premier brouillon personnalisé, puis relisez-le. Aucun message n’est envoyé.</p><section class="scan-panel"><strong>1. Comprendre le prospect</strong><p class="note">${e(record.website||'Ajoutez le site officiel dans la fiche contact.')}<br>Jusqu’à 4 pages publiques : page renseignée, accueil et rubriques pertinentes. Aucun accès aux espaces privés.</p><button id="scan-site" class="primary" ${!record.website||demo||!canEdit?'disabled':''}>Analyser le site et préparer le brouillon</button><p class="note muted">${demo?'Analyse désactivée en démonstration.':!canEdit?'Analyse réservée aux éditeurs de la marque.':'Rédaction structurée à partir d’extraits du site. Sans service IA payant.'}</p><p id="scan-state" role="status" aria-live="polite"></p><div id="scan-sources"></div></section><section><strong>2. Votre proposition</strong><label for="draft-offer">Offre à présenter pour ${e(brand.name)}</label><textarea id="draft-offer" maxlength="1200" placeholder="Décrivez l’offre validée de cette marque…">${e(offer)}</textarea><label for="draft-sender">Signature</label><select id="draft-sender">${team.map(m=>`<option value="${e(m.display_name)}" ${m.user_id===owner?.user_id?'selected':''}>${e(m.display_name)}</option>`).join('')}</select><button id="draft-build">Préparer / actualiser le texte</button></section><section class="draft-result"><strong>3. Relire et copier</strong><label for="draft-subject">Objet</label><input id="draft-subject"><label for="draft-text">Message</label><textarea id="draft-text" style="min-height:290px"></textarea><p class="note muted">Vérifiez l’actualité de l’offre et la pertinence du passage retenu. Le brouillon n’est pas conservé après fermeture.</p><label class="checkrow"><input type="checkbox" id="draft-reviewed"> J’ai relu et vérifié ce message.</label><p class="error" id="draft-error" role="status"></p></section><div class="form-footer"><button id="draft-back">Retour à la fiche</button><button id="draft-copy" class="primary" disabled>Copier objet et message</button></div>`;
 const q=id=>dialog.querySelector('#'+id);const active=()=>dialog.open&&dialog.dataset.draft===token;
 const finish=()=>{controller.abort();dialog.dataset.draft='';};
 q('draft-close').onclick=()=>{finish();dialog.close();};q('draft-back').onclick=()=>{finish();back();};
 const invalidate=()=>{q('draft-reviewed').checked=false;q('draft-copy').disabled=true;};
 q('draft-reviewed').onchange=()=>{q('draft-copy').disabled=!q('draft-reviewed').checked||!q('draft-text').value.trim();};
 for(const id of ['draft-text','draft-subject','draft-offer','draft-sender'])q(id).addEventListener('input',invalidate);
 function build(){q('draft-error').textContent='';const offer=q('draft-offer').value.trim();if(!offer){q('draft-error').textContent='Décrivez d’abord l’offre de cette marque.';return;}const choice=q('draft-evidence');const fact=scan?.evidence[Number(choice?.value||0)];const result=composeDraft({brand:brand.name,contact:record.name,sender:q('draft-sender').value,offer,evidence:fact?[fact]:[]});q('draft-subject').value=result.subject;q('draft-text').value=result.body;invalidate();}
 q('draft-build').onclick=build;
 q('scan-site').onclick=async()=>{const btn=q('scan-site');btn.disabled=true;scan=null;q('scan-sources').innerHTML='';q('draft-text').value='';q('draft-subject').value='';invalidate();q('scan-state').textContent='Consultation des pages publiques en cours…';q('draft-error').textContent='';try{
  const result=await store.scan(record.id,controller.signal);if(!active())return;scan=result;
  q('scan-state').textContent=`${result.pages.length} page(s) lue(s) · ${new Date(result.scannedAt).toLocaleString('fr-FR')}`;
  q('scan-sources').innerHTML=`${result.evidence.length?`<label for="draft-evidence">Passage retenu pour l’accroche</label><select id="draft-evidence">${result.evidence.map((f,i)=>`<option value="${i}">${e(f.excerpt)}</option>`).join('')}</select><p id="evidence-source" class="note"></p>`:'<p>Aucun passage suffisamment pertinent détecté. Le texte restera général : ajoutez votre observation après vérification.</p>'}<details open><summary>Pages consultées et limites</summary><ul>${result.pages.map(p=>`<li><a href="${e(p.url)}" target="_blank" rel="noopener noreferrer">${e(p.title||p.url)}</a></li>`).join('')}</ul>${result.warnings.map(w=>`<p class="note">${e(w)}</p>`).join('')}</details>`;
  const source=()=>{const f=result.evidence[Number(q('draft-evidence').value)];q('evidence-source').innerHTML=`Source de l’accroche : <a href="${e(f.url)}" target="_blank" rel="noopener noreferrer">${e(f.title||f.url)}</a>`;};if(q('draft-evidence')){source();q('draft-evidence').onchange=()=>{source();invalidate();q('draft-error').textContent='Cliquez sur « Préparer / actualiser le texte » pour utiliser ce passage.';};}build();
 }catch(err){if(active()&&err.name!=='AbortError')q('scan-state').textContent=err.message;}finally{if(active())btn.disabled=false;}};
 q('draft-copy').onclick=async()=>{try{await navigator.clipboard.writeText('Objet : '+q('draft-subject').value+'\n\n'+q('draft-text').value);q('draft-error').textContent='Brouillon copié. Aucun envoi effectué.';}catch{q('draft-error').textContent='Copie indisponible : sélectionnez le texte pour le copier.';}};
 build();
}
