import {config} from './config.mjs';
export class RemoteStore {
 constructor(){this.token=null;this.user=null;this.expires=0;}
 async login(email,password){const r=await fetch(config.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw Error('Connexion refusée. Vérifiez votre compte et votre mot de passe.');this.token=data.access_token;this.expires=Date.now()+data.expires_in*1000;this.user=data.user;return data.user;}
 async request(path,method='GET',body){if(!this.token||Date.now()>=this.expires)throw Error('Session expirée. Déconnectez-vous puis reconnectez-vous.');const r=await fetch(config.url+'/rest/v1/'+path,{method,headers:{apikey:config.publishableKey,Authorization:'Bearer '+this.token,'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw Error(r.status===409?'Ce dossier existe déjà ou une relation est invalide.':r.status===403?'Votre rôle ne permet pas cette action.':'Enregistrement impossible. Vérifiez votre connexion et vos droits.');return r.status===204?[]:r.json();}
 async all(table,filter=''){let result=[];for(let offset=0;;offset+=500){const page=await this.request(`${table}?select=*&order=id&limit=500&offset=${offset}${filter}`);result.push(...page);if(page.length<500)return result;}}
 async load(){return {brands:await this.all('crm_brands'),members:await this.all('crm_members'),records:await this.all('crm_records'),events:await this.all('crm_events')};}
 async save(record){const {id,version,created_at,updated_at,...body}=record;if(id){const rows=await this.request(`crm_records?id=eq.${id}&version=eq.${version}`,'PATCH',body);if(!rows.length)throw Error('Cette fiche a changé depuis votre ouverture. Actualisez avant de réessayer.');return rows[0];}return (await this.request('crm_records','POST',body))[0];}
 async brand(name){return this.request('rpc/crm_create_brand','POST',{brand_name:name});}
 async logout(){if(this.token)await fetch(config.url+'/auth/v1/logout',{method:'POST',headers:{apikey:config.publishableKey,Authorization:'Bearer '+this.token}}).catch(()=>{});this.token=null;this.user=null;}
}
export class DemoStore {
 constructor(){this.user={id:'demo-jefferson',email:'Compte de démonstration'};this.reset();}
 reset(){const date=new Date().toLocaleDateString('sv-SE');this.data={brands:[{id:'demo-nanaye',name:'Nanayé',description:'Espace de démonstration'},{id:'demo-brand',name:'Autre marque · exemple'}],members:[{id:'m1',brand_id:'demo-nanaye',user_id:'demo-jefferson',display_name:'Jefferson · démo',role:'owner'},{id:'m2',brand_id:'demo-nanaye',user_id:'demo-lyne',display_name:'Lyne · démo',role:'editor'},{id:'m3',brand_id:'demo-brand',user_id:'demo-jefferson',display_name:'Jefferson · démo',role:'owner'}],records:[],events:[]};const add=(kind,name,status,extra={})=>this.data.records.push({id:crypto.randomUUID(),brand_id:'demo-nanaye',owner_id:'demo-jefferson',kind,name,status,email:'',phone:'',website:'',notes:'Exemple fictif — aucune démarche réelle.',source:'Démonstration',due_date:null,amount_cents:0,paid_cents:0,quantity:1,related_id:null,archived:false,version:1,created_at:new Date().toISOString(),...extra});add('contact','Maison des Ondes · fictif','À qualifier');add('contact','Les Jardins du Soleil · fictif','Qualifié',{owner_id:'demo-lyne'});add('deal','Week-end entre amies · exemple','Échange en cours',{amount_cents:45000,quantity:10});add('deal','Collection été · exemple','À préparer',{amount_cents:84000,owner_id:'demo-lyne'});add('task','Qualifier le besoin du groupe','À faire',{due_date:date});add('task','Préparer les visuels','En cours',{owner_id:'demo-lyne',due_date:date});add('order','Groupe de 10 · exemple','En production',{amount_cents:45000,paid_cents:22500,owner_id:'demo-lyne',quantity:10});add('product','Maillot groupe · exemple','À valider',{amount_cents:4500});}
 async load(){return structuredClone(this.data);}
 async save(record){const index=this.data.records.findIndex(x=>x.id===record.id);if(index>=0&&record.version!==this.data.records[index].version)throw Error('Fiche modifiée. Actualisez.');const r={...record,id:record.id||crypto.randomUUID(),version:(record.version||0)+1,updated_at:new Date().toISOString()};if(index>=0)this.data.records[index]=r;else this.data.records.push(r);this.data.events.unshift({id:crypto.randomUUID(),brand_id:r.brand_id,record_id:r.id,actor_id:this.user.id,record_name:r.name,action:index>=0?'Modification':'Création',created_at:new Date().toISOString()});return r;}
 async brand(name){const id=crypto.randomUUID();this.data.brands.push({id,name});this.data.members.push({id:crypto.randomUUID(),brand_id:id,user_id:this.user.id,display_name:'Jefferson · démo',role:'owner'});return id;}
 async logout(){}
}
